- src: https://github.com/robertdebock/ansible-role-update_package_cache
  name: robertdebock.update_package_cache
  version: 2.0.1
- src: https://github.com/robertdebock/ansible-role-core_dependencies
  name: robertdebock.core_dependencies
  version: 2.0.0
- src: https://github.com/robertdebock/ansible-role-epel
  name: robertdebock.epel
  version: 3.0.2
- src: https://github.com/geerlingguy/ansible-role-pip
  name: geerlingguy.pip
  version: 2.0.0
- src: https://github.com/robertdebock/ansible-role-bootstrap
  name: robertdebock.bootstrap
  version: 5.0.3
- src: https://github.com/robertdebock/ansible-role-update
  name: robertdebock.update
  version: 3.0.2
- src: https://github.com/robertdebock/ansible-role-users
  name: robertdebock.users
  version: 5.0.1
- src: https://github.com/robertdebock/ansible-role-firewall
  name: robertdebock.firewall
  version: 5.0.1
- src: https://github.com/robertdebock/ansible-role-hostname
  name: robertdebock.hostname
  version: 3.0.0
- src: https://github.com/robertdebock/ansible-role-postfix
  name: geerlingguy.postfix
  version: 2.0.0
- src: https://github.com/robertdebock/ansible-role-openssl
  name: robertdebock.openssl
  version: 2.0.0
- src: https://github.com/robertdebock/ansible-role-certbot
  name: robertdebock.certbot
  version: 2.1.0
- src: https://github.com/nginxinc/ansible-role-nginx
  name: nginxinc.nginx
  version: 0.17.2
- src: https://github.com/nginxinc/ansible-role-nginx-config
  name: nginxinc.nginx_config
  version: 0.2.0
- src: https://github.com/robertdebock/ansible-role-cron
  name: robertdebock.cron
  version: 2.0.0
- src: https://github.com/robertdebock/ansible-role-logrotate
  name: robertdebock.logrotate
  version: 2.0.0
- src: https://github.com/justin-p/ansible-role-gophish
  name: justin_p.gophish
  version: 1.0.5
