- name: robertdebock.update_package_cache
  version: 1.1.14
- name: robertdebock.core_dependencies
  version: 1.5.0
- name: robertdebock.epel
  version: 2.5.2
- name: geerlingguy.pip
  version: 2.0.0
- name: robertdebock.bootstrap
  version: 4.3.2
- name: robertdebock.update
  version: 2.3.5
- name: robertdebock.users
  version: 4.4.0
- name: robertdebock.firewall
  version: 5.0.1
- name: robertdebock.hostname
  version: 2.0.7
- name: geerlingguy.postfix
  version: 2.0.0
- name: robertdebock.openssl
  version: 1.3.5
- name: robertdebock.certbot
  version: 1.0.4
- name: nginxinc.nginx
  version: 0.17.2
- name: nginxinc.nginx_config
  version: 0.2.0
- name: robertdebock.cron
  version: 1.7.0
- name: robertdebock.logrotate
  version: 1.4.5
- name: justin_p.gophish
  version: 1.0.2
